fullnameOverride: alerta

read:
  ingress:
    enabled: true
    hosts:
      - host: alerta-read.example.local
        paths:
          - /

web:
  ingress:
    enabled: true
    hosts:
      - host: alerta-web.example.local
        paths:
          - /

alertaAdminUsers:
  - admin
alertaAdminPassword: admin

alertaConfig: |
  CORS_ORIGINS = [r'https?://.*\.example\.local']

alertaWebConfig: |
  {
    "endpoint": "http://alerta-read.example.local"
  }
