fullnameOverride: alerta

read:
  ingress:
    enabled: true
    hosts:
      - host: alerta-read.example.local
        paths:
          - /

web:
  ingress:
    enabled: true
    hosts:
      - host: alerta-web.example.local
        paths:
          - /

config:
  crosOrigins:
    - r'https?://.*\.example\.local'
  endpoint: http://alerta-read.example.local
