fullnameOverride: alerta

read:
  route:
    enabled: true
    host: alerta-read.example.local

web:
  route:
    enabled: true
    host: alerta-web.example.local

config:
  crosOrigins:
    - r'https?://.*\.example\.local'
  endpoint: http://alerta-read.example.local

postgresql:
  enabled: false

database:
  url: mongodb://alerta:alerta@mongodb.example.local:3717/alerta
