{{- if .Values.read.ingress.enabled -}}
{{- $fullName := include "alerta-helm.fullname" . -}}
{{- $svcPort := .Values.read.service.port -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}-read
  labels:
    app: {{ include "alerta-helm.fullname" . }}-read
    {{- include "alerta-helm.labels" . | nindent 4 }}
  {{- with .Values.read.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.read.ingress.tls }}
  tls:
    {{- range .Values.read.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.read.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ . }}
            backend:
              serviceName: {{ $fullName }}-read
              servicePort: {{ $svcPort }}
          {{- end }}
    {{- end }}
  {{- end }}
