apiVersion: v1
kind: Secret
metadata:
  name: {{ include "alerta-helm.fullname" . }}
  labels:
    {{- include "alerta-helm.labels" . | nindent 4 }}
type: Opaque
data:
  alerta-admin-users: {{ .Values.alertaAdminUsers | join ", " | b64enc | quote }}
  {{ if .Values.alertaAdminPassword }}
  alerta-admin-password: {{ .Values.alertaAdminPassword | b64enc | quote }}
  {{ else }}
  alerta-admin-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{ end }}
  {{ if .Values.alertaAdminKey }}
  alerta-admin-key: {{ .Values.alertaAdminKey | b64enc | quote }}
  {{ end }}